language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
  - npm i nyc --save-dev
  - npm install codeclimate-test-reporter istanbul -g
addons:
    code_climate:
        repo_token: e16ebd70d00fbda9d1bead6cc084677219518639a24b1a1c5baa3155b559a9cf
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info