<<<<<<< HEAD
language: node_js
node_js:
    - "stable"
install:
    - npm install
script:
    - npm run coveralls
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
=======

>>>>>>> af7b6bd3674eab53f72daf9372494885a0a1843f
